#%RAML 1.0
title: Employee
/getEmployee:
  get:
    description: Gets Emp data
    responses:
      200:
        body:
          application/json:
           example: 
            {
              "employees":[
                  {
                    "empid":"e101",
                    "name":"Sree"
                  },
                  {
                    "empid":"e102",
                    "name":"Dk"
                  }
                ]
            }
